In [1]:
def dy_dx(x):
    return 2*x

In [2]:
dy_dx(2)

4

In [3]:
import torch

In [4]:
def nested_fun(x):
    return 2*x*torch.cos(x**2)

In [5]:
a=torch.tensor(2.0)
nested_fun(a)

tensor(-2.6146)

In [6]:
X=torch.tensor(1.0,requires_grad=True)

In [7]:
X

tensor(1., requires_grad=True)

In [8]:
y=X**2

In [9]:
y

tensor(1., grad_fn=<PowBackward0>)

In [10]:
X.backward()

In [11]:
X.grad

tensor(1.)

## Second Function

In [12]:
X=torch.tensor(1.0,requires_grad=True)

In [13]:
X

tensor(1., requires_grad=True)

In [14]:
y=X**2
y

tensor(1., grad_fn=<PowBackward0>)

In [15]:
z=torch.sin(y)
z

tensor(0.8415, grad_fn=<SinBackward0>)

## Manual Process

In [16]:


X=torch.tensor(2.0)
y=torch.tensor(0.0)

w=torch.tensor(1.0)
b=torch.tensor(0.0)

In [17]:
# BCE
def binary_cross_entropy_loss(prediction, target):

    # Small value to avoid numerical problems
    # Why? Because log(0) is undefined (-infinity)
    # So we never want prediction to become exactly 0 or exactly 1
    epsilon = 1e-8

    # Clamp means: force values to stay inside a safe range
    # If prediction < epsilon → set it to epsilon
    # If prediction > (1 - epsilon) → set it to (1 - epsilon)
    # This prevents log(0) when computing:
    # log(prediction) or log(1 - prediction)

    prediction = torch.clamp(prediction, epsilon, 1 - epsilon) # torch.clamp(x, min_value, max_value)

    # BCE formula:
    # target * log(prediction)     → used when target = 1
    # (1 - target) * log(1 - prediction) → used when target = 0
    # Negative sign makes loss positive

    loss = -(target * torch.log(prediction) +
             (1 - target) * torch.log(1 - prediction))

    return loss

In [18]:
# Forward pass
z = w * X + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [19]:
loss

tensor(2.1269)

In [21]:
#derivative
#1
dloss_by_pred=(y_pred-y)/(y_pred*(1-y_pred))
#2
dy_pred_dz=y_pred*(1-y_pred)

dz_dw=X
dz_db=1

dL_dw=dloss_by_pred*dy_pred_dz*dz_dw
dL_db=dloss_by_pred*dy_pred_dz*dz_db


In [22]:
dL_dw

tensor(1.7616)

In [23]:
dL_db

tensor(0.8808)

### Using autograd

In [24]:
X=torch.tensor(2.0)
y=torch.tensor(0.0)

w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [ ]:
z=w*X+b

In [27]:
z

tensor(2., grad_fn=<AddBackward0>)

In [28]:
y_pred=torch.sigmoid(z)

In [29]:
y_pred

tensor(0.8808, grad_fn=<SigmoidBackward0>)

In [30]:
loss=binary_cross_entropy_loss(y_pred,y)

In [31]:
loss

tensor(2.1269, grad_fn=<NegBackward0>)

In [32]:
loss.backward()

In [33]:
w.grad

tensor(1.7616)

# Using multiple value

In [34]:
X=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [35]:
X

tensor([1., 2., 3.], requires_grad=True)

In [36]:
y=(X**2).mean()

In [37]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [38]:
y.backward()

In [39]:
X.grad

tensor([0.6667, 1.3333, 2.0000])

In [40]:
#Option 1
X.grad.zero_()


tensor([0., 0., 0.])

In [41]:
#Option 2
X.requires_grad_(False)

tensor([1., 2., 3.])

In [42]:
X

tensor([1., 2., 3.])

In [44]:
y=X**2
y

tensor([1., 4., 9.])

In [45]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [49]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [50]:
z = x.detach()
z

tensor(2.)

In [51]:
x

tensor(2., requires_grad=True)

In [52]:
y = x ** 2

In [53]:
y

tensor(4., grad_fn=<PowBackward0>)

In [54]:
y1 = z ** 2
y1

tensor(4.)

In [55]:
y.backward()

In [56]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [57]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [58]:
y = x ** 2

In [59]:
y

tensor(4., grad_fn=<PowBackward0>)

In [60]:
y.backward()