In [248]:
import torch
print(torch.__version__)

2.10.0+cpu


In [249]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")
    
else:
    print("GPU is not available")

GPU is not available


In [250]:
a=torch.empty(2,3)
a

tensor([[ 6.2500, 12.2500, 20.2500],
        [ 6.2500, 12.2500, 20.2500]])

In [251]:
type(a)

torch.Tensor

In [252]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [253]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [254]:
torch.rand(2,3)

tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601]])

In [255]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [256]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [257]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [258]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [260]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [261]:
x.shape

torch.Size([2, 3])

In [262]:
torch.empty_like(x)

tensor([[100, 200, 300],
        [400, 500, 600]])

In [263]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [264]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [265]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [266]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [267]:
#floor
x=x*100

In [268]:
x//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [269]:
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [270]:
c=torch.tensor([-1,-2,-3,-4])

In [271]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [272]:
c=torch.tensor([1,2,3,4])

In [273]:
torch.neg(c)

tensor([-1, -2, -3, -4])

In [274]:
d=torch.tensor([1.2,2.4,3.11,4.5])

In [275]:
torch.round(d)

tensor([1., 2., 3., 4.])

In [276]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [277]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [278]:
torch.clamp(d,min=1,max=2)

tensor([1.2000, 2.0000, 2.0000, 2.0000])

# Reduction Operation:

In [279]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [280]:
e

tensor([[8., 8., 4.],
        [4., 1., 0.]])

In [281]:
torch.sum(e)

tensor(25.)

In [282]:
torch.sum(e,dim=0)

tensor([12.,  9.,  4.])

In [283]:
torch.sum(e,dim=1)

tensor([20.,  5.])

In [284]:
torch.mean(e)

tensor(4.1667)

In [285]:
torch.mean(e,dim=0)

tensor([6.0000, 4.5000, 2.0000])

In [286]:
torch.median(e)

tensor(4.)

In [287]:
# max and min
torch.max(e)

tensor(8.)

In [288]:
torch.min(e)

tensor(0.)

In [289]:
torch.prod(e)

tensor(0.)

In [290]:
torch.std(e)

tensor(3.3714)

In [291]:
torch.var(e)

tensor(11.3667)

In [292]:
#argmin,argmax
torch.argmax(e)

tensor(0)

In [293]:
torch.argmin(e)

tensor(5)

## Matrix operation

In [294]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [295]:
f

tensor([[4, 3, 8],
        [7, 4, 6]])

In [296]:
g

tensor([[0, 1],
        [9, 9],
        [8, 0]])

In [297]:
torch.matmul(f,g)

tensor([[91, 31],
        [84, 43]])

## Dot Product

In [298]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [299]:
torch.dot(vector1,vector2)

tensor(11)

In [300]:
f.shape

torch.Size([2, 3])

In [301]:
torch.transpose(f,0,1)

tensor([[4, 7],
        [3, 4],
        [8, 6]])

In [302]:
g

tensor([[0, 1],
        [9, 9],
        [8, 0]])

In [303]:
g.shape

torch.Size([3, 2])

In [304]:
torch.transpose(g,0,1)

tensor([[0, 9, 8],
        [1, 9, 0]])

In [305]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [306]:
torch.det(h)

tensor(-301.)

In [307]:
torch.inverse(h)

tensor([[ 0.1429,  0.0000,  0.0000],
        [ 0.0498, -0.0930,  0.1628],
        [-0.2193,  0.2093, -0.1163]])

## Comparison Operation

In [308]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

In [309]:
# grather then
i>j

tensor([[False, False, False],
        [False, False,  True]])

In [310]:
#less then
i<j

tensor([[ True, False,  True],
        [ True, False, False]])

In [311]:
#  not equal to
i !=j

tensor([[ True, False,  True],
        [ True, False,  True]])

# Special Function

In [312]:
k=torch.tensor([10,20,30])
k

tensor([10, 20, 30])

In [313]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [314]:
# exp
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [315]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [316]:
#sigmoid
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [317]:
#softmax
torch.softmax(k.float(), dim=0)

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

In [318]:
torch.relu(k)

tensor([10, 20, 30])

In [319]:
import torch
data=torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [320]:
X=data[:,0:2]
y=data[:,2]

In [321]:
X

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [322]:
y

tensor([3, 4, 5])

## Weight initialization

In [323]:
def initialize_parameters():
    parameters={}
    parameters['W1']=torch.ones((2,2))*0.1
    parameters['b1']=torch.ones((2,1))
    
    parameters['W2']=torch.ones((2,1))*0.1
    parameters['b2']=torch.ones((1,1))
    
    return parameters

### better way

In [324]:
def initialize_parameters(layer_dims):
    torch.manual_seed(3)
    parameters={}
    L=len(layer_dims)

    for l in range(1,L):
        parameters["W"+str(l)]=torch.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters["b" + str(l)] = torch.zeros( (layer_dims[l], 1))

    return parameters

In [325]:
initialize_parameters( [2,2,1] )

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

## Forward Propagration

In [326]:
def linear_forward( A_prev, W, b ) :
  Z = torch.matmul( W.T , A_prev ) + b
  return Z

In [327]:
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2

  for l in range(1,L+1):
    A_prev = A

    wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    A = linear_forward( A_prev, wl, bl )

  return A, A_prev


In [328]:
X

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [329]:
params = initialize_parameters([2,2,1])
X_sample = X[0].reshape(2,1).float()
y_hat, A1 = L_layer_forward(X_sample,params)

In [330]:
y_hat

tensor([[0.1000]])

In [331]:
A1

tensor([[0.5000],
        [0.5000]])

In [332]:
(y-y_hat) ** 2

tensor([[ 8.4100, 15.2100, 24.0100]])

In [333]:
def update_parameters(parameters, y, y_hat, A1, X, lr=0.001):

    err_signal = 2 * (y - y_hat)

     #  Save OLD W2 values before updating
    W2_00_old = parameters['W2'][0, 0].item()
    W2_10_old = parameters['W2'][1, 0].item()

    # Update Layer 2




    parameters['W2'][0, 0] += lr * err_signal * A1[0, 0]
    parameters['W2'][1, 0] += lr * err_signal * A1[1, 0]
    parameters['b2'][0, 0] += lr * err_signal #


    parameters['W1'][0, 0] += lr * err_signal * parameters['W2'][0, 0] * X[0, 0]
    parameters['W1'][0, 1] += lr * err_signal * parameters['W2'][0, 0] * X[1, 0]
    parameters['b1'][0, 0] += lr * err_signal * parameters['W2'][0, 0]

    parameters['W1'][1, 0] += lr * err_signal * parameters['W2'][1, 0] * X[0, 0]
    parameters['W1'][1, 1] += lr * err_signal * parameters['W2'][1, 0] * X[1, 0]
    parameters['b1'][1, 0] += lr * err_signal * parameters['W2'][1, 0]

    return parameters

In [334]:
# using loop

params = initialize_parameters([2, 2, 1])
epochs = 5

for i in range(epochs):
    epoch_loss = 0
    for j in range(X.shape[0]):
        # Prepare sample
        X_sample = X[j].reshape(2, 1).float()
        y_sample = y[j].float()

        # Forward
        y_hat, A1 = L_layer_forward(X_sample, params)
        y_hat_scalar = y_hat[0, 0]

        # Update
        params = update_parameters(params, y_sample, y_hat_scalar, A1, X_sample)

        # Loss calculation
        loss = (y_sample - y_hat_scalar) ** 2
        epoch_loss += loss.item()

    print(f"Epoch - {i+1} Loss - {epoch_loss / X.shape[0]}")

Epoch - 1 Loss - 14.67866039276123
Epoch - 2 Loss - 13.701451301574707
Epoch - 3 Loss - 12.494118690490723
Epoch - 4 Loss - 11.040447076161703
Epoch - 5 Loss - 9.366330782572428
