In [98]:
import torch
import torch.nn as nn

In [99]:
# class Model(nn.Module):
#     def __init__(self,num_features):
#         super().__init__()
#         self.linear=nn.Linear(num_features,1)
#         self.sigmoid=nn.Sigmoid()
#     def forward(self,features):
#         out=self.linear(features)
#         out=self.sigmoid(out)
        
#         return out

## Version 2

In [100]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     #layer 1

#     self.linear1 = nn.Linear(num_features,3)
#     self.relu = nn.ReLU()

#     #layer 2
#     self.linear2 = nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

In [101]:
# Version 3


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [102]:
# Create dataset
features=torch.rand(10,5)

In [103]:
features

tensor([[0.8697, 0.5521, 0.0448, 0.4373, 0.4866],
        [0.4704, 0.5731, 0.2373, 0.4223, 0.9749],
        [0.8873, 0.1404, 0.4651, 0.1534, 0.4373],
        [0.9500, 0.9026, 0.7410, 0.1472, 0.7392],
        [0.9116, 0.8299, 0.0097, 0.0940, 0.5790],
        [0.9177, 0.7786, 0.9314, 0.0306, 0.8647],
        [0.6415, 0.4338, 0.9644, 0.1178, 0.9795],
        [0.3260, 0.7515, 0.9348, 0.6075, 0.7560],
        [0.8912, 0.1347, 0.5861, 0.5068, 0.4458],
        [0.0052, 0.3866, 0.2662, 0.5959, 0.6124]])

In [104]:
features.shape[1]

5

In [105]:
#create model
model=Model(features.shape[1])

In [106]:
#calling model for forward pass
model.forward(features)

tensor([[0.3273],
        [0.3199],
        [0.3363],
        [0.3056],
        [0.3248],
        [0.3044],
        [0.3132],
        [0.3147],
        [0.3271],
        [0.3465]], grad_fn=<SigmoidBackward0>)

In [107]:
#or
model(features)

tensor([[0.3273],
        [0.3199],
        [0.3363],
        [0.3056],
        [0.3248],
        [0.3044],
        [0.3132],
        [0.3147],
        [0.3271],
        [0.3465]], grad_fn=<SigmoidBackward0>)

In [113]:
# show model weights for the current version
# print('linear1 weights:', model.linear1.weight)
# print('linear2 weights:', model.linear2.weight)
model.network[0].weight


Parameter containing:
tensor([[ 0.3778,  0.0424, -0.2922,  0.4384,  0.3573],
        [-0.1208,  0.2174, -0.0104, -0.4159,  0.1014],
        [ 0.1256,  0.1996,  0.3343, -0.0267,  0.1801]], requires_grad=True)

In [115]:

model.network[2].weight

Parameter containing:
tensor([[-0.2335,  0.5770, -0.3991]], requires_grad=True)

In [109]:
# visualize

#!pip install torchinfo

In [110]:
from torchinfo import summary

summary( model,input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Extra

In [116]:
# Base Class
class Rectangle:
    def __init__(self, length, width):
        print("Rectangle constructor called")
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width


# Child Class (Square inherits Rectangle)
class Square(Rectangle):
    def __init__(self, side):
        print("Square constructor called")
        super().__init__(side, side)   # Calls Rectangle constructor

    def square_info(self):
        return f"Square area: {self.area()}"


# Child Class (Cube inherits Square)
class Cube(Square):
    def __init__(self, side):
        print("Cube constructor called")
        super().__init__(side)   # Calls Square constructor

    def volume(self):
        return self.length ** 3


# Create Object
cube = Cube(4)

print("Area:", cube.area())
print("Volume:", cube.volume())

Cube constructor called
Square constructor called
Rectangle constructor called
Area: 16
Volume: 64
