In [39]:
import torch
import torch.nn as nn

In [40]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        
        return out

## Version 2

In [41]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    #layer 1

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    #layer 2
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [42]:
# Create dataset
features=torch.rand(10,5)

In [43]:
features

tensor([[0.7041, 0.2653, 0.2286, 0.6110, 0.9896],
        [0.2972, 0.8509, 0.4886, 0.4952, 0.9614],
        [0.5468, 0.7634, 0.6587, 0.3185, 0.1002],
        [0.0786, 0.0100, 0.1709, 0.1856, 0.8466],
        [0.6712, 0.3019, 0.0174, 0.8126, 0.9460],
        [0.1302, 0.3846, 0.1753, 0.9839, 0.6310],
        [0.1136, 0.0357, 0.8877, 0.2037, 0.3556],
        [0.3382, 0.3410, 0.7059, 0.0405, 0.4544],
        [0.3963, 0.8682, 0.9148, 0.6393, 0.8405],
        [0.3847, 0.3043, 0.7329, 0.4015, 0.7988]])

In [44]:
features.shape[1]

5

In [45]:
#create model
model=Model(features.shape[1])

In [46]:
#calling model for forward pass
model.forward(features)

tensor([[0.3120],
        [0.3465],
        [0.3779],
        [0.3274],
        [0.3161],
        [0.3553],
        [0.3580],
        [0.3517],
        [0.3550],
        [0.3357]], grad_fn=<SigmoidBackward0>)

In [47]:
#or
model(features)

tensor([[0.3120],
        [0.3465],
        [0.3779],
        [0.3274],
        [0.3161],
        [0.3553],
        [0.3580],
        [0.3517],
        [0.3550],
        [0.3357]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights for the current version
print('linear1 weights:', model.linear1.weight)
print('linear2 weights:', model.linear2.weight)

AttributeError: 'Model' object has no attribute 'linear'