In [164]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [165]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [166]:
df.shape

(569, 33)

In [167]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [168]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


## Train Test split

In [169]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

#### scaling

In [170]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [171]:
X_train

array([[-0.84834011, -1.02247227, -0.87053929, ..., -0.87498412,
        -0.50727788,  0.43800213],
       [ 1.89342236,  0.49130435,  1.76161474, ...,  0.49509904,
        -1.07058778, -0.70644151],
       [-0.79012859,  0.11913906, -0.82863814, ..., -1.29460482,
        -0.56008818, -0.43258646],
       ...,
       [-0.69116901,  1.18312082, -0.70462766, ..., -0.98913204,
         0.53932633, -0.92169383],
       [ 0.4526873 ,  3.25400378,  0.54267221, ...,  1.37161952,
         0.96821001,  2.06197386],
       [ 2.20776455,  0.70364406,  2.16369648, ...,  1.68279199,
        -1.35544336, -0.71320336]])

In [172]:
y_train

398    B
237    M
522    B
317    M
206    B
      ..
310    B
231    B
305    B
259    M
564    M
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [173]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Numpy arrays to PyTorch tensors

In [174]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [175]:
X_train_tensor.shape

torch.Size([455, 30])

In [176]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [177]:
class MysimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    def loss_function(self,y_pred,y):
        #clamp
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
        
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss
        
        
    

## Important Parameters

In [178]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [179]:
# create model
model = MysimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.088498147354653
Epoch: 2, Loss: 2.9452519545307165
Epoch: 3, Loss: 2.801670627732434
Epoch: 4, Loss: 2.658153088917303
Epoch: 5, Loss: 2.5113109705796033
Epoch: 6, Loss: 2.358336651574309
Epoch: 7, Loss: 2.2092615066102317
Epoch: 8, Loss: 2.060154215665867
Epoch: 9, Loss: 1.9161107269631157
Epoch: 10, Loss: 1.7761832979798617
Epoch: 11, Loss: 1.640894950509747
Epoch: 12, Loss: 1.510269417783191
Epoch: 13, Loss: 1.3871449794218382
Epoch: 14, Loss: 1.2785233762422337
Epoch: 15, Loss: 1.184637512771029
Epoch: 16, Loss: 1.1049149079940963
Epoch: 17, Loss: 1.0381226354238113
Epoch: 18, Loss: 0.9826347288913158
Epoch: 19, Loss: 0.9366961854994722
Epoch: 20, Loss: 0.8986363283574024
Epoch: 21, Loss: 0.8670043845967277
Epoch: 22, Loss: 0.8406117154657053
Epoch: 23, Loss: 0.8185064595973833
Epoch: 24, Loss: 0.799924426564238
Epoch: 25, Loss: 0.784245534461865


In [180]:
model.bias

tensor([-0.1921], dtype=torch.float64, requires_grad=True)

In [181]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5701754093170166


In [182]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      